# Default storage location
data_path = "./data"

# Global log level
log_level = "info"

[backtest]
initial_equity = 10000.0

[exchange.bybit_testnet]
rest_url = "https://api-testnet.bybit.com"
ws_url = "wss://stream-testnet.bybit.com"
api_key = ""
api_secret = ""

[exchange.bybit_mainnet]
rest_url = "https://api.bybit.com"
ws_url = "wss://stream.bybit.com"
api_key = ""
api_secret = ""
